package trainee.task.university.core.database.entity;

public enum Faculty {
    FACULTY_OF_LAW,
    FACULTY_OF_AIR_NAVIGATION_ELECTRONICS_AND_TELECOMMUNICATIONS,
    FACULTY_OF_AGRICULTURE_CONSTRUCTION_AND_DESIGN,
    FACULTY_OF_CYBER_SECURITY_COMPUTER_AND_SOFTWARE_ENGINEERING,
    FACULTY_OF_FLYING_MACHINES,
    MECHANICAL_FACULTY,
    FACULTY_OF_ECONOMICS_AND_BUSINESS_ADMINISTRATION,
    FACULTY_OF_ENVIRONMENTAL_SAFETY_ENGINEERING_AND_TECHNOLOGIES,
    FACULTY_OF_TRANSPORT_MANAGEMENT_AND_LOGISTICS;
}
