package trainee.task.university.core.database.entity;

public enum Speciality {
    AIRDROME_EQUIPMENT,
    AIR_TRANSPORT_ECONOMICS,
    BUSINESS_ANALYTICS_AND_DIGITAL_ECONOMICS,
    MARKETING,
    FINANCES_AND_BUSINESS_TECHNOLOGIES,
    PSYCHOLOGY,
    PRACTICAL_PSYCHOLOGY,
    SOCIOLOGY,
    LINGUISTICS,
    BIOCYBERNATICS_AND_AEROSPACE_MEDICINE,
    ECOLOGY,
    CHEMISTRY_AND_CHEMICAL_INDUSTRY,
    AIRCRAFT_ENGINES,
    AUTOMATION_AND_ENERGY_MANAGEMENT,
    AERODYNAMICS_AND_FLIGHT_SAFETY,
    GAS_TURBINE_SYSTEMS,
    AIRPORT_TECHNOLOGIES,
    FLYING_MACHINES_CONSTRUCTION,
    CONSTITUTIONAL_AND_ADMINISTRATIVE_RIGHTS,
    CIVIL_LAW_AND_PROCESSING,
    CRIMINAL_RIGHTS_AND_PROCESSING,
    COMPUTER_TECHNOLOGIES
}
